# Site settings
title: MIPCDVIZ
email:
description: > # this means to ignore newlines until "baseurl:"
is this where all the information goes? 
*ehem* testing testing

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
